version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      time: "20:00"
    groups:
      nestjs:
        patterns:
          - "@nestjs/*"
      react:
        patterns:
          - "react"
          - "react-dom"
          - "@types/react"
          - "@types/react-dom"
      next:
        patterns:
          - "next"
          - "eslint-config-next"
    ignore:
      - dependency-name: "@heroicons/react"
      - dependency-name: "chalk"
